[connections.supabase]
SUPABASE_URL = "https://khgwpiflumfizqpzmthx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoZ3dwaWZsdW1maXpxcHptdGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjA2MDIxNzIsImV4cCI6MjAzNjE3ODE3Mn0.Rj-GZdvZDNuMaDIsJV4fKS6Nmf0nfXfX5va4M26crSI"